# Configuration for librarian-puppet lists the modules we depend upon.
# 
forge "http://forge.puppetlabs.com"

mod "puppetlabs/apache"

mod "puppetlabs/postgresql"

mod "python",
   :git => "https://github.com/stankevich/puppet-python"

mod "dgu_ckan",
   :path => "/vagrant/puppet/modules/dgu_ckan"
