# Configuration for librarian-puppet lists the modules we depend upon.
# 
forge "http://forge.puppetlabs.com"

mod "puppetlabs/apache"

mod "puppetlabs/postgresql"
mod "puppetlabs/nodejs"
mod "saz/memcached"
mod "saz/sudo"
mod "example42/puppi"
mod "example42/monitor"
mod "datagovuk/solr",
   :git => "https://github.com/example42/puppet-solr"

mod "datagovuk/python",
   :git => "https://github.com/stankevich/puppet-python"

mod "datagovuk/dgu_ckan",
   :path => "/vagrant/puppet/modules/dgu_ckan"
